# Generated by Django 2.2.7 on 2020-10-21 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GallaryImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(db_column='FILE', max_length=200, null=True, upload_to='')),
                ('is_active', models.BooleanField(db_column='IS_ACTIVE', default=True)),
                ('is_deleted', models.BooleanField(db_column='IS_DELETED', default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CREATED_DATE', null=True)),
                ('last_updated_date', models.DateTimeField(auto_now=True, db_column='LAST_UPDATED_DATE', null=True)),
            ],
            options={
                'db_table': 'GallaryImages',
            },
        ),
    ]
