# Generated by Django 2.2.7 on 2020-10-21 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GallaryApp', '0003_auto_20201021_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallaryimages',
            name='file',
            field=models.FileField(db_column='FILE', null=True, upload_to=''),
        ),
    ]
